version: '3.4'

services:
  repose:
    image: rackerlabs/repose
    ports:
      - 8182:8080
    environment:
      KEYSTONE_USER: ${KEYSTONE_USER}
      KEYSTONE_PASSWORD: ${KEYSTONE_PASSWORD}
    volumes:
      - ./repose-config:/etc/repose
  backend:
    image: itzg/web-debug-server:0.0.2