version: '3.7'

services:
  repose-public:
    image: rackerlabs/repose:${REPOSE_VERSION:-9.0.1.0}
    ports:
      - 8180:8080
    env_file:
      - common.env
    environment:
      KEYSTONE_USER: ${KEYSTONE_USER}
      KEYSTONE_PASSWORD: ${KEYSTONE_PASSWORD}
      BACKEND_HOST: public-api
      BACKEND_PORT: 8080
    volumes:
      - ../repose-api-public/repose-config:/etc/repose
    networks:
      - infra
  repose-admin:
    image: rackerlabs/repose:${REPOSE_VERSION:-9.0.0.0}
    ports:
      - 8188:8080
    env_file:
      - common.env
    environment:
      KEYSTONE_USER: ${KEYSTONE_USER}
      KEYSTONE_PASSWORD: ${KEYSTONE_PASSWORD}
      BACKEND_HOST: admin-api
      BACKEND_PORT: 8080
    volumes:
      - ../repose-api-admin/repose-config:/etc/repose
    networks:
      - infra

networks:
  infra:
    external: true
    name: telemetry-infra_default
