version: '3.2'

services:
  mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: ${MYSQL_INITIAL_PASSWORD:-initialpw}
      MYSQL_ONETIME_PASSWORD: "true"

volumes:
  mysql:
